[[redirects]]
  force = true
  from = "/api/*"
  to = "http://143.198.92.250:8080/api/:splat"
  status = 200
[[redirects]]
  force = true
  from = "/media/*"
  to = "hhttp://143.198.92.250:8080/api/:splat"
  status = 200
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200