import { tas, sepatu, baju, kotak } from '../../assets/images/admin'

export const kelolaTransaksi = [
  {
    id: 1,
    label: 'Edward Pieters',
    image: tas,
    kode: 'Kode Penyewaan: #S100019042023',
    kLoker: 'Small-01',
    barang: 'Tas ransel',
    chckin: '19 April 2023',
    chcout: '21 April 2023',
    location: 'Inventron Surabaya',
    rp: '(Tunai) Rp. 45.000,-',
    status: 'Penitipan Selesai',
  },
  {
    id: 2,
    label: 'Dinda Oktaviani',
    image: sepatu,
    kode: 'Kode Penyewaan: #S100024042023',
    kLoker: 'Small-09',
    barang: 'Sepatu',
    chckin: '21 April 2023',
    chcout: '24 April 2023',
    location: 'Inventron Jakarta',
    rp: '(Tunai) Rp. 30.000,-',
    status: 'Sedang Disewa',
  },
  {
    id: 3,
    label: 'Nabila Azzahra',
    image: baju,
    kLoker: 'Medium-17',
    barang: 'Pakaian',
    chckin: '03 Mei 2023',
    chcout: '07 Mei 2023',
    location: 'Inventron Malang',
    kode: 'Kode Penyewaan: #S100003052023',
    rp: '(Tunai) Rp. 80.000,-',
    status: 'Penitipan Selesai',
  },
  {
    id: 4,
    label: 'Abdul Rahman',
    image: kotak,
    kLoker: 'Medium-22',
    barang: 'Kardus',
    chckin: '24 Mei 2023 2023',
    chcout: '28 Mei 2023 2023',
    location: 'Inventron Bandung',
    kode: 'Kode Penyewaan: #S100024052023',
    rp: '(Tunai) Rp. 45.000,-',
    status: 'Sedang Disewa',
  },
]
